submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 2880
cpus_per_task: 4
gpus_per_node: 0
tasks_per_node: 1
mem_gb: 64
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: standard
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null