dataset_path: ${oc.env:HOME}/datasets/herbarium_scans_senckenberg
rate_limit_wait: true
image_list: data/handwritten.txt
image_index: 0
n_images: 100
batch_size: 5
img_max_size: 4096
batch_prompt: "In the following, you will receive a batch of identification tasks. Each task consists of at least one image. All tasks are independent from each other. For each task, identify the specified information above and provide the results in the mentioned format. Separate the results of each task with two newlines. Do not include any additional text or explanations."
llm:
  remote_server: null
  temperature: null
  options: {}
  model_name: "gemini-2.5-pro"
  prompt: "
    You are an expert in identifying and extracting information from herbarium labels.
    Your task is to read the handwritten or printed text from the provided images and extract relevant information such as:
    - Species name
    - Collection date
    - Collector's name
    - Country/State
    - Location
    - Region
    - Notes

    Please provide the extracted information in a structured format as linewise key value pairs separated by ': ' without any text before and after this information.
    Provide the collector's name in the format 'First Last' (e.g., 'John Doe').
    Format dates like 'YYYY-MM-DD' and ensure that the species name is in a standard format (e.g., 'Genus species').
    Provide the country/state in a structured format like 'Country: State. Translate terms, especially the country, to German if necessary.
    Provide the location in a structured format like 'Town/City, Location Details'.
    If any information is not available, leave it blank.
    "
preprocessors:
  grounding_dino:
    model_name: "IDEA-Research/grounding-dino-tiny"
    enabled: true
    box_threshold: 0.25
    text_threshold: 0.3
    max_outputs: 5 # Use only the five most confident boxes
    prompt: "Identify the herbarium label in the image. The label is typically a rectangular area containing handwritten text or printed text and contains information like the species name, collection date, collector's name, location, and notes. Sometimes the text is not on a separate label but directly on the image. Focus on extracting the text from this area."
    device: "cpu" # Use "cuda" for GPU or "cpu" for CPU
    log_output: true


hydra:
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}-${hydra.job.name}
    subdir: ${sanitize:${hydra:job.override_dirname}}
    #,llm.prompt=${shorthash:${llm.prompt}},grounding_dino.prompt=${shorthash:${preprocessors.grounding_dino.prompt}}
  run:
    dir: outputs/${hydra.job.name}-${now:%Y-%m-%d_%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys:
          - llm.prompt
          - preprocessors.grounding_dino.prompt